api:
  address: "localhost:8081"
mysql:
  host: 127.0.0.1
  port: 3306
  db: test
  username: "root"
  password: "123456"
redis:
  address: localhost
  password: ""
  database: 1
  port: 6379
log:
  level: info
  env: develop
  path: "/Users/harry/Documents/logs/"
server:
  host: 0.0.0.0
  port: 8081
  master: "N"
  secret: "crawlab"
  register:
    # mac地址 或者 ip地址，如果是ip，则需要手动指定IP
    type: "mac"
    ip: ""
spider:
  path: "/app/spiders"
task:
  workers: 4
other:
  tmppath: "/tmp"